name: Build Windows 32-bit App

on:
  push:
    branches: [main]  # Change if your default branch is different
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # Set a known stable version

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Generate plugin and CMake config files
        run: flutter create --platforms=windows .

      - name: Run 32-bit build script
        shell: cmd
        run: build_windows.bat

      - name: Search for .exe files in entire workspace
        shell: cmd
        continue-on-error: true
        run: dir /s /b *.exe

      - name: List common output directories
        shell: cmd
        continue-on-error: true
        run: |
          dir build\win32\Release
          dir build\windows\runner\Release
          dir build
