name: Build Windows 32-bit App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Get dependencies
        run: flutter pub get

      - name: Create build_win32.bat script
        run: |
          echo @echo off > build_win32.bat
          echo rmdir /s /q build\win32 >> build_win32.bat
          echo mkdir build\win32 >> build_win32.bat
          echo cd build\win32 >> build_win32.bat
          echo cmake ../../windows -G "Visual Studio 17 2022" -A Win32 -DCMAKE_BUILD_TYPE=Release >> build_win32.bat
          echo IF %%ERRORLEVEL%% NEQ 0 (echo CMake generation failed! & exit /b %%ERRORLEVEL%%) >> build_win32.bat
          echo cmake --build . --config Release >> build_win32.bat
          echo IF %%ERRORLEVEL%% NEQ 0 (echo Build failed! & exit /b %%ERRORLEVEL%%) >> build_win32.bat
          echo cd .. >> build_win32.bat
          echo echo ✅ Build complete >> build_win32.bat

      - name: Run build_win32.bat
        run: build_win32.bat

      - name: Upload 32-bit Windows build
        uses: actions/upload-artifact@v4
        with:
          name: win32-build
          path: build/win32/Release/
