name: Build Windows 32-bit App

on:
  push:
    branches: [main]  # Change if your default branch is different
  workflow_dispatch:

jobs:
  build-win32:
    runs-on: windows-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'  # Set a known stable version

      - name: Enable Windows desktop support
        run: flutter config --enable-windows-desktop

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Run 32-bit build script
        shell: cmd
        run: build_windows.bat

      - name: List built files (debugging)
        shell: cmd
        run: dir build\win32\Release

      - name: Zip Win32 build
        shell: cmd
        run: powershell Compress-Archive -Path build\win32\Release\* -DestinationPath win32-build.zip

      - name: Upload zipped build
        uses: actions/upload-artifact@v4
        with:
          name: win32-build
          path: win32-build.zip
