name: Build Windows 64-bit App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-win64:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Enable Windows desktop
        run: flutter config --enable-windows-desktop

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows x64 app
        run: flutter build windows

      - name: List built files (for verification)
        shell: cmd
        run: dir build\windows\runner\Release

      - name: Zip build output
        shell: cmd
        run: powershell Compress-Archive -Path build\windows\runner\Release\* -DestinationPath win64-build.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: win64-build
          path: win64-build.zip

